"""baseline schema

Revision ID: 2edb173af8ee
Revises:
Create Date: 2026-08-04 21:35:52.182372
"""

from alembic import op
import sqlalchemy as sa


revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: table creation order below is topologically sorted by FK
    # dependency (Postgres rejects a FK to a table that doesn't exist yet,
    # unlike SQLite). data_source_integrations <-> datasets is a genuine
    # cycle, broken by deferring the dataset_id FK until after datasets
    # exists (added via op.create_foreign_key below).
    op.create_table('billing_webhook_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('login_otp_challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_otp_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_otp_challenges_email'), ['email'], unique=False)

    op.create_table('rate_limit_counters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bucket_key', sa.String(length=255), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_key', name='uq_rate_limit_counter_bucket')
    )
    with op.batch_alter_table('rate_limit_counters', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_counters_expires_at', ['expires_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('active_workspace_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('subscription_plan', sa.String(), nullable=False),
    sa.Column('billing_provider', sa.String(), nullable=True),
    sa.Column('billing_customer_id', sa.String(), nullable=True),
    sa.Column('billing_subscription_id', sa.String(), nullable=True),
    sa.Column('subscription_current_period_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('outlook_forecast_dataset_id', sa.String(), nullable=True),
    sa.Column('outlook_forecast_date_column', sa.String(), nullable=True),
    sa.Column('outlook_forecast_value_column', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_owner_id'), ['owner_id'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('source_files_json', sa.Text(), nullable=True),
    sa.Column('user_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='uploadstatus'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('processing_stage', sa.String(length=64), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('data_source_integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('connection_mode', sa.String(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('refresh_interval_hours', sa.Integer(), nullable=False),
    sa.Column('auto_analyze', sa.Integer(), nullable=False),
    sa.Column('dashboard_plan_locked', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'syncing', 'error', 'disconnected', name='integrationstatus'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    # dataset_id -> datasets.id FK added below via op.create_foreign_key,
    # once the datasets table exists (see NOTE above upgrade()).
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_source_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_source_integrations_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_source_integrations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('integration_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schema_json', sa.Text(), nullable=True),
    sa.Column('data_summary', sa.Text(), nullable=True),
    sa.Column('cleaned_report_json', sa.Text(), nullable=True),
    sa.Column('dashboard_plan_json', sa.Text(), nullable=True),
    sa.Column('dashboard_plan_locked', sa.Integer(), nullable=False),
    sa.Column('business_classification', sa.String(), nullable=True),
    sa.Column('mapping_spec_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['data_source_integrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_integration_id'), ['integration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_upload_id'), ['upload_id'], unique=False)

    op.create_foreign_key(
        'data_source_integrations_dataset_id_fkey',
        'data_source_integrations', 'datasets',
        ['dataset_id'], ['id'],
        ondelete='SET NULL',
    )

    op.create_table('analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('dashboards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('layout_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('dataset_relations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('source_dataset_id', sa.String(), nullable=False),
    sa.Column('target_dataset_id', sa.String(), nullable=False),
    sa.Column('source_column', sa.String(), nullable=False),
    sa.Column('target_column', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_relations_source_dataset_id'), ['source_dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_relations_target_dataset_id'), ['target_dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_relations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_recurring_summaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_label', sa.String(length=255), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('email_html_snapshot', sa.Text(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_scheduled', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'kind', 'period_start', name='uq_workspace_recurring_summary_period')
    )
    with op.batch_alter_table('workspace_recurring_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_recurring_summaries_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_timeline_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('display_label', sa.String(length=512), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('themes_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_timeline_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_timeline_snapshots_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_timeline_snapshots_ref_id'), ['ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_timeline_snapshots_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_timeline_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_timeline_snapshots_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_timeline_snapshots_ref_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_timeline_snapshots_dataset_id'))

    op.drop_table('workspace_timeline_snapshots')
    with op.batch_alter_table('workspace_recurring_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_recurring_summaries_workspace_id'))

    op.drop_table('workspace_recurring_summaries')
    with op.batch_alter_table('dataset_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_relations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_relations_target_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_relations_source_dataset_id'))

    op.drop_table('dataset_relations')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboards_workspace_id'))

    op.drop_table('dashboards')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_dataset_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_dataset_id'))

    op.drop_table('analyses')

    op.drop_constraint(
        'data_source_integrations_dataset_id_fkey',
        'data_source_integrations',
        type_='foreignkey',
    )

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_upload_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_integration_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('data_source_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_source_integrations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_data_source_integrations_dataset_id'))

    op.drop_table('data_source_integrations')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_workspace_id'))

    op.drop_table('uploads')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('rate_limit_counters', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_counters_expires_at')

    op.drop_table('rate_limit_counters')
    with op.batch_alter_table('login_otp_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_otp_challenges_email'))

    op.drop_table('login_otp_challenges')
    op.drop_table('billing_webhook_events')
    # ### end Alembic commands ###
